#* * * * *
#- - - - -
#| | | | |
#| | | | ----- day of week (0 - 6) (Sunday =0 or =7)
#| | | ------- Month (1 - 12)
#| | --------- Day (1 - 31)
#| ----------- Hour (0 - 23)
#------------- Minute (0 - 59)

note_reminder:
  cron: '*/1 * * * *'   # Runs once per minute
  class: NoteReminderWorker